vim.cmd('cnoreabbrev Wq wq')
vim.cmd('cnoreabbrev WQ wq')
vim.cmd('cnoreabbrev Wqa wqa')
vim.cmd('cnoreabbrev W w')
vim.cmd('cnoreabbrev Q q')
vim.cmd('cnoreabbrev Qa qa')
vim.cmd('cnoreabbrev Bd bd')
vim.cmd('cnoreabbrev wrap set wrap')
vim.cmd('cnoreabbrev nowrap set nowrap')
vim.cmd('cnoreabbrev E e')