# From https://docs.helix-editor.com/languages.html

############################################
#               Git
############################################
[[language]]
name = "git-commit"
scope = "git.commitmsg"
file-types = [{ glob = "COMMIT_EDITMSG" }, { glob = "MERGE_MSG" }]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
rulers = [101]
text-width = 100

[[language]]
name = "git-rebase"
scope = "source.gitrebase"
file-types = [{ glob = "git-rebase-todo" }, { glob = "git-revise-todo" }]
injection-regex = "git-rebase"
comment-token = "#"
indent = { tab-width = 2, unit = "\t" }

############################################
#               Python
############################################
[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config.basedpyright.analysis]
autoSearchPaths = true
typeCheckingMode = "basic"
diagnosticMode = "openFilesOnly"
autoImportCompletions = true

[[language]]
name = "python"
scope = "source.python"
injection-regex = "py(thon)?"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt", { glob = ".python_history" }, { glob = ".pythonstartup" }, { glob = ".pythonrc" }, { glob = "SConstruct" }, { glob = "SConscript" }]
shebangs = ["python", "uv"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
language-servers = ["basedpyright"]
formatter = { command = "ruff" , args = ["format"] }
# formatter = { command = "bash", args = ["-c", "ruff check --fix - | ruff format -"] }
indent = { tab-width = 4, unit = "    " }


############################################
#               Terraform
############################################
# [[language]]
# name = "hcl"
# scope = "source.hcl"
# injection-regex = "(hcl|tf|nomad)"
# language-id = "terraform"
# file-types = ["hcl", "tf", "nomad"]
# comment-token = "#"
# block-comment-tokens = { start = "/*", end = "*/" }
# indent = { tab-width = 2, unit = "  " }
# language-servers = [ "terraform-ls" ]
# auto-format = true
# formatter = { command = "terraform" , args = ["fmt"] }
#
# [[language]]
# name = "tfvars"
# scope = "source.tfvars"
# language-id = "terraform-vars"
# file-types = ["tfvars"]
# comment-token = "#"
# block-comment-tokens = { start = "/*", end = "*/" }
# indent = { tab-width = 2, unit = "  " }
# language-servers = [ "terraform-ls" ]
# auto-format = true
# grammar = "hcl"